version: "3"

services:
  portfolio:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - INPROGRESS=false
      - GITHUB_TOKEN=ghp_token
      - DISCORD_WEBHOOK_TOKEN=token
      - DISCORD_WEBHOOK_ID=id
      - API_URL=api_url
    volumes:
      - .:/usr/Portfolio
  portfolio-api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "5050:5050"
    environment:
      - PORT=5050
      - DATABASE_URL=mongodb+srv://<user>:<password>@cluster0.rpnpo6x.mongodb.net/test?retryWrites=true&w=majority
    volumes:
      - ./api:/usr/api
