import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="w-screen h-screen flex bg-gradient-to-tl from-[#091645] to-[#150838]">
        {children}
      </body>
    </html>
  );
}
