import Particle from "./components/particle";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="w-screen min-h-screen flex bg-gradient-to-b from-[#091645] to-[#2a2575]">
        {children}
        <Particle />
      </body>
    </html>
  );
}
